#!/bin/bash
# Manual deployment script for GitHub Pages

echo "🚀 Deploying to GitHub Pages..."

# Build the notes
echo "📝 Building notes..."
./build.sh

# Add all generated files
echo "📁 Adding generated files..."
git add pages/notes.html
git add notes-html/*.html

# Check if there are changes
if git diff --staged --quiet; then
    echo "✅ No changes to deploy"
    exit 0
fi

# Commit and push
echo "💾 Committing changes..."
git commit -m "Deploy: Update generated HTML files

Generated by build script on $(date)"

echo "🚀 Pushing to GitHub..."
git push origin main

echo "✅ Deployment complete!"
echo "🌐 Your site will be available at: https://qunlexie.github.io"
